language: scala

jdk:
- openjdk6

env:
  global:
    - TRAVIS_UNDERCOVER=true
  matrix:
    - "EMACS=emacs24 ENSIME_TEST_SERVER_VERSION=2.11.5"

install:
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

script:
  - test/run_emacs_tests.sh #2>&1 | tee stdout | grep "Starting test"

after_failure:
  - cat stdout
